[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython",
    "numpy",
    "packaging",
]

[flake8]
max-line-length=120

[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
line_length = 120
profile = "black"
multi_line_output = 3
